# Generated by Django 4.1 on 2022-08-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50)),
                ('app_link', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=30)),
                ('sub_Category', models.CharField(max_length=30)),
                ('score', models.IntegerField()),
                ('logo', models.CharField(max_length=100)),
            ],
        ),
    ]
