# Generated by Django 4.1 on 2022-08-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playstore', '0002_alter_app_category_alter_app_logo_alter_app_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='score',
            field=models.IntegerField(),
        ),
    ]
