# Generated by Django 4.1 on 2022-08-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playstore', '0003_alter_app_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
