# Generated by Django 4.1 on 2022-08-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playstore', '0006_alter_app_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='sub_Category',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
